libraries:
  Movies:
    library_type: movie
    operations:
      delete_unmanaged_collections: true
    metadata_path:
      - repo: movies_awards
      - repo: movies_bestof
      - repo: movies_charts
      - repo: movies_franchises
      - repo: movies_genre_popular
      - repo: movies_genre_top
      - repo: movies_originals
      - repo: movies_kids
      - repo: movies_sports
  Movies - 4K:
    library_type: movie
    operations:
      delete_unmanaged_collections: true
    metadata_path:
      - repo: movies_awards
      - repo: movies_bestof
      - repo: movies_charts
      - repo: movies_franchises
      - repo: movies_genre_popular
      - repo: movies_genre_top
      - repo: movies_originals
      - repo: movies_kids
  Movies - 4K DV:
    library_type: movie
    operations:
      delete_unmanaged_collections: true
    metadata_path:
      - repo: movies_awards
      - repo: movies_bestof
      - repo: movies_charts
      - repo: movies_franchises
      - repo: movies_genre_popular
      - repo: movies_genre_top
      - repo: movies_originals
      - repo: movies_kids
  TV Shows:
    library_type: show
    operations:
      delete_unmanaged_collections: true
    metadata_path:
      - repo: shows_awards
      - repo: shows_bestof
      - repo: shows_charts
      - repo: shows_genre_popular
      - repo: shows_genre_top
      - repo: shows_networks
      - repo: shows_kids
  TV Shows - 4K:
    library_type: show
    operations:
      delete_unmanaged_collections: true
    metadata_path:
      - repo: shows_awards
      - repo: shows_bestof
      - repo: shows_charts
      - repo: shows_genre_popular
      - repo: shows_genre_top
      - repo: shows_networks
      - repo: shows_kids
  TV Shows - 4K DV:
    library_type: show
    operations:
      delete_unmanaged_collections: true
    metadata_path:
      - repo: shows_awards
      - repo: shows_bestof
      - repo: shows_charts
      - repo: shows_genre_popular
      - repo: shows_genre_top
      - repo: shows_networks
      - repo: shows_kids
settings:                                       # Can be individually specified per library as well
  cache: true
  cache_expiration: 60
  sync_mode: sync
  show_unmanaged: false
  show_filtered: false
  show_missing: fale
  save_missing: false
  run_again_delay: 2
  asset_directory: config/assets
  asset_folders: true
  assets_for_all: false
  released_missing_only: false
  create_asset_folders: false
  missing_only_released: false
  delete_below_minimum: true
  notifiarr_collection_creation: false
  notifiarr_collection_addition: false
  notifiarr_collection_removing: false
  tvdb_language: default
  show_missing_assets: true
  only_filter_missing: false
  minimum_items: 5
  asset_depth: 0
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  default_collection_order:
  item_refresh_delay: 0
  delete_not_scheduled: false
  show_options: false
  ignore_ids:
  ignore_imdb_ids:
  playlist_sync_to_users: all
  verify_ssl: true
  custom_repo: https://github.com/arkyntech/pmm-configs/main/
plex:                                           # Can be individually specified per library as well
  url: http://plex:32400
  token: XXXXXXXXXXXXX
  timeout: 120
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:
  apikey: 
  language: en
omdb:
  apikey: 

trakt:
  client_id: 
  client_secret: 

